source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-paginate-v2"
gem "jekyll-archives"
gem "jekyll-include-cache"
gem "jekyll-last-modified-at"
gem "jekyll-toc"
